### ISSUE TITLE
antab time format always assumed t be "Day_no  hh:mm.mm" ?

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/casa-vlbi#2]
Which ANTAB time formats are supported by append_antab and friends?
According to http://www.aips.nrao.edu/cgi-bin/ZXHLP2.PL?ANTAB there are multiple options:
```
Day_no  hh.hh        col1 col2 ... etc
Day_no  hh:mm.mm     col1 col2 ... etc
Day_no  hh:mm:ss.ss  col1 col2 ... etc
```
However, the lines at
https://github.com/jive-vlbi/casa-vlbi/blob/a3d71b45cd2a7e9486f2af6faba2e69fe49970dd/importtsys.py#L179
seem to assume it is always decimal minutes, i.e. "Day_no  hh:mm.mm" in the antab files.

This may be a problem, because e.g. antab files from EVN for gv025 has this form:
`063 19:59:57   28.0   26.5 ...`
If I parse this using the importtsys syntax I get:
```
>>> math.modf(float("19:59:57".split(':')[1]))
(0.0, 59.0)
```
which will lead to the "seconds" part being listed as 0 in the generated timestamp. 
It should be relatively easy to check which data format is used. Am I missing something, or should this be added (to support EVN data, and other data)?

**Comment by varenius** [comment]
Note: This is sneaky, because it will silently assume 0 seconds and hence make the timestames "approximately" correct, within the minute. But, with rapid schedules (VGOS can have 10 second scans) this may result in Tsys being assigned to the wrong source, in a completely different direction.

**Comment by varenius** [comment]
Na, I misread the logic: the problem is actually at https://github.com/varenius/casa-vlbi/blob/master/casavlbitools/fitsidi.py#L224 . The same conceptual fix should apply though. Will see if I can make a pull request also for that one.

**Comment by kettenis** [comment]
Hi Eskil,
Thanks for the bug report. The lack of support for other timestamp formats isn't intentional. I'll take a closer look at the pull request in a bit.
I fear parsing ANTAB files will always be somewhat problematic. I've seen quite a few errors that AIPS doesn't report. Ultimately the best thing to do is to have Tsys and gain curves in the FITS-IDI files from the get go. We're working on that at JIVE. Note that DiFX can already do this; the VLBA uses difx2fits to create FITS-IDI files with the data included.
Thanks again,
Mark

**Comment by kettenis** [comment]
Hi Eskil,
I merged the pull request. Thanks again.
