### ISSUE TITLE
Polarisations always assumed to be the same in these tools?

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/casa-vlbi#6]
It seems polarisations are always assumed to be the same, e.g https://github.com/jive-vlbi/casa-vlbi/blob/master/casavlbitools/fitsidi.py#L319 which assumes R then L for tsys1, tsys2. What if someone has L,R? What if we have H,V och X,Y? The antab file can specify this, but it seems these scripts always assume R then L? Would it be worth making the tools a bit more clever to match the actual polarisations between data and antab?

**Comment by kettenis** [comment]
Hi Eskil,
Doesn't look like the antab file can specify anything but R and L. At least X would be problematic since it is used to mark dummy columns. And I don't think AIPS would handle H,V either.
There are quite a few implicit assumptions in how the data is structured. The FITS-IDI standard strongly suggests the order should be 'R,L' (or 'X,Y'), and I think both difx2fits and the tools used at JIVE enforce that order.
We have some data in the EVN archive where POLTYA and POLTYB aren't properly specified, so I have to be careful with making things to strict.
So my preference would be to leave things as they are now unless we encounter data that has these labels reversed.
